# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32K\n\x05\x43\x61\x63he\x12 \n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponse\x12 \n\x03Set\x12\x0b.SetRequest\x1a\x0c.SetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=15
  _globals['_GETREQUEST']._serialized_end=40
  _globals['_GETRESPONSE']._serialized_start=42
  _globals['_GETRESPONSE']._serialized_end=70
  _globals['_SETREQUEST']._serialized_start=72
  _globals['_SETREQUEST']._serialized_end=112
  _globals['_SETRESPONSE']._serialized_start=114
  _globals['_SETRESPONSE']._serialized_end=144
  _globals['_CACHE']._serialized_start=146
  _globals['_CACHE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
